name: Build documentation

on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: ${{ secrets.INSTANCE }}
  ARTIFACT: ${{ secrets.ARTIFACT }}
  DOCKER_VERSION: ${{ secrets.DOCKER_VERSION }}

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: stagecodes
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=stagecodes/otr-docs-prod:$(git rev-parse --short HEAD)
          docker build --no-cache -t $IMAGE_TAG .
          docker tag $IMAGE_TAG stagecodes/otr-docs-prod:latest
          docker push $IMAGE_TAG
          docker push stagecodes/otr-docs-prod:latest

  deploy:
    name: Deploy
    environment: Production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull stagecodes/otr-docs-prod:latest
            docker stop otr-docs || true
            docker rm otr-docs || true
            docker run -d -p 3800:80 --restart=always --name otr-docs stagecodes/otr-docs-prod:latest
